name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  sonar:
    name: SonarQube Scan
    runs-on: buildjet-4vcpu-ubuntu-2204
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run tests with coverage
        run: |
          yarn test --coverage --reporter=verbose
          # Ensure coverage directory exists
          mkdir -p coverage

      - name: Check SonarQube Configuration
        run: |
          if [ -z "$SONAR_TOKEN" ] || [ -z "$SONAR_HOST_URL" ]; then
            echo "⚠️ SonarQube secrets not configured. Skipping analysis."
            echo "Required secrets: SONAR_TOKEN, SONAR_HOST_URL"
            echo "Please configure these in repository settings to enable SonarQube analysis."
            echo "SKIP_SONAR=true" >> $GITHUB_ENV
          else
            echo "✅ SonarQube configuration found. Proceeding with analysis."
            echo "SKIP_SONAR=false" >> $GITHUB_ENV
          fi
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: SonarQube Scanner
        if: env.SKIP_SONAR == 'false'
        uses: sonarsource/sonarqube-scan-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        if: env.SKIP_SONAR == 'false'
        uses: sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Quality Gate Status
        if: env.SKIP_SONAR == 'false'
        run: |
          echo "Quality Gate Status: ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}"
          if [ "${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}" != "PASSED" ]; then
            echo "Quality Gate failed"
            exit 1
          fi
